import { useEffect, useState } from "react";
import { api } from "../api/client";
import type { Character, Crew, CrewRole, Fleet } from "../types/models";
const ASSIGNABLE_ROLES: CrewRole[] = ["Offizier", "Kommandant", "Stellvertreter", "Mitglied"];
export function CrewPanel({character,onCharacterUpdated}:{character:Character;onCharacterUpdated:(c:Character)=>void}){
 const [allCrews,setAllCrews]=useState<Crew[]>([]);const [myCrew,setMyCrew]=useState<Crew|null>(null);const [fleets,setFleets]=useState<Fleet[]>([]);const [newCrewName,setNewCrewName]=useState("");const [newFleetName,setNewFleetName]=useState("");const [joinCrewId,setJoinCrewId]=useState("");const [joinFleetId,setJoinFleetId]=useState("");const [error,setError]=useState<string|null>(null);const [busy,setBusy]=useState(false);
 async function refresh(){const [crews,fs]=await Promise.all([api.listCrews(),api.listFleets()]);setAllCrews(crews);setFleets(fs);setMyCrew(crews.find(c=>c.id===character.crewId)??null);}
 useEffect(()=>{refresh().catch(e=>setError(e.message));},[character.crewId]);
 async function updateChar(){onCharacterUpdated(await api.getCharacter(character.id));await refresh();}
 async function createCrew(e:React.FormEvent){e.preventDefault();setBusy(true);setError(null);try{await api.createCrew(character.id,newCrewName);await updateChar();}catch(e){setError(e instanceof Error?e.message:"Fehler");}finally{setBusy(false);}}
 async function joinCrew(e:React.FormEvent){e.preventDefault();setBusy(true);setError(null);try{await api.joinCrew(joinCrewId,character.id);await updateChar();}catch(e){setError(e instanceof Error?e.message:"Fehler");}finally{setBusy(false);}}
 async function assign(target:string,role:CrewRole){if(!myCrew)return;try{await api.assignCrewRole(myCrew.id,character.id,target,role);await refresh();}catch(e){setError(e instanceof Error?e.message:"Fehler");}}
 async function createFleet(e:React.FormEvent){e.preventDefault();if(!myCrew)return;setBusy(true);try{await api.createFleet(myCrew.id,character.id,newFleetName);await refresh();}catch(e){setError(e instanceof Error?e.message:"Fehler");}finally{setBusy(false);}}
 async function joinFleet(e:React.FormEvent){e.preventDefault();if(!myCrew)return;setBusy(true);try{await api.joinFleet(joinFleetId,myCrew.id,character.id);await refresh();}catch(e){setError(e instanceof Error?e.message:"Fehler");}finally{setBusy(false);}}
 if(!myCrew){const joinable=allCrews.filter(c=>c.factionId===character.factionId);return <div style={{border:"1px solid #ddd",borderRadius:8,padding:16}}><h3>Crew</h3>{error&&<p style={{color:"crimson"}}>{error}</p>}<form onSubmit={createCrew} style={{display:"flex",gap:8,marginBottom:12}}><input placeholder="Neue Crew gründen..." value={newCrewName} onChange={e=>setNewCrewName(e.target.value)} required/><button disabled={busy}>Gründen</button></form>{joinable.length>0&&<form onSubmit={joinCrew} style={{display:"flex",gap:8}}><select value={joinCrewId} onChange={e=>setJoinCrewId(e.target.value)} required><option value="">Crew wählen...</option>{joinable.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button disabled={busy}>Beitreten</button></form>}</div>}
 const isCaptain=myCrew.members.find(m=>m.characterId===character.id)?.role==="Captain";const myFleet=fleets.find(f=>f.memberCrewIds.includes(myCrew.id));const joinableFleets=fleets.filter(f=>!f.memberCrewIds.includes(myCrew.id));
 return <div><div style={{border:"1px solid #ddd",borderRadius:8,padding:16,marginBottom:16}}><h3>Crew: {myCrew.name}</h3>{error&&<p style={{color:"crimson"}}>{error}</p>}<ul>{myCrew.members.map(m=><li key={m.characterId}>{m.characterId===character.id?"Du":m.characterId} — <strong>{m.role}</strong>{isCaptain&&m.role!=="Captain"&&<select style={{marginLeft:8}} defaultValue="" onChange={e=>e.target.value&&assign(m.characterId,e.target.value as CrewRole)}><option value="">Rolle ändern...</option>{ASSIGNABLE_ROLES.map(r=><option key={r}>{r}</option>)}</select>}</li>)}</ul></div>
 <div style={{border:"1px solid #ddd",borderRadius:8,padding:16}}><h3>Flotte</h3>{myFleet?<><p>Deine Crew gehört zur Flotte <strong>{myFleet.name}</strong>.</p><p>Mitglieds-Crews: {myFleet.memberCrewIds.length}</p></>:isCaptain?<><form onSubmit={createFleet} style={{display:"flex",gap:8,marginBottom:12}}><input placeholder="Neue Flotte gründen..." value={newFleetName} onChange={e=>setNewFleetName(e.target.value)} required/><button disabled={busy}>Flotte gründen</button></form>{joinableFleets.length>0&&<form onSubmit={joinFleet} style={{display:"flex",gap:8}}><select value={joinFleetId} onChange={e=>setJoinFleetId(e.target.value)} required><option value="">Flotte wählen...</option>{joinableFleets.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select><button disabled={busy}>Flotte beitreten</button></form>}</>:<p>Nur der Captain kann die Crew einer Flotte anschließen oder eine Flotte gründen.</p>}</div></div>;
}
