export type GameView = "overview"|"profile"|"skills"|"progression"|"inventory"|"missions"|"map"|"travel"|"events"|"combat"|"organizations"|"territory"|"marketplace"|"shop"|"village"|"crew"|"fusion"|"dev";
type Entry={id:GameView;label:string;icon:string};
const groups:{title:string;items:Entry[]}[]=[
 {title:"Charakter",items:[{id:"overview",label:"Übersicht",icon:"◈"},{id:"profile",label:"Profil & Origin",icon:"◎"},{id:"skills",label:"Fähigkeiten",icon:"✦"},{id:"progression",label:"Training",icon:"▲"},{id:"inventory",label:"Inventar",icon:"▣"}]},
 {title:"Welt",items:[{id:"missions",label:"Missionen",icon:"◆"},{id:"map",label:"Weltkarte",icon:"⌖"},{id:"travel",label:"Reisen",icon:"➜"},{id:"events",label:"Weltereignisse",icon:"☄"},{id:"combat",label:"Kampf",icon:"⚔"}]},
 {title:"Macht & Politik",items:[{id:"organizations",label:"Organisationen",icon:"♜"},{id:"territory",label:"Gebiete",icon:"⚑"}]},
 {title:"Wirtschaft",items:[{id:"shop",label:"Shop",icon:"◇"},{id:"marketplace",label:"Marktplatz",icon:"⇄"}]},
];
export function Sidebar({active,onChange,worldId,collapsed,showDev=false,onToggle}:{active:GameView;onChange:(v:GameView)=>void;worldId:string;collapsed:boolean;showDev?:boolean;onToggle:()=>void}){
 const extra:Entry[]=[]; if(worldId==="ninja_welt")extra.push({id:"village",label:"Dorf",icon:"⌂"}); if(worldId==="ozeanwelt")extra.push({id:"crew",label:"Crew & Flotte",icon:"☸"}); if(worldId==="avalon")extra.push({id:"fusion",label:"Knight-Fusion",icon:"✧"});
 return <aside className={`sidebar ${collapsed?"collapsed":""}`}><div className="sidebar-brand"><div className="brand-mark">N</div>{!collapsed&&<div><b>PROJECT NEXUS</b><span>V1 · {worldId.replaceAll("_"," ")}</span></div>}<button className="sidebar-toggle" onClick={onToggle}>{collapsed?"›":"‹"}</button></div><nav className="sidebar-nav">{groups.map(g=><div className="nav-group" key={g.title}>{!collapsed&&<div className="nav-title">{g.title}</div>}{g.items.map(i=><button key={i.id} className={active===i.id?"active":""} onClick={()=>onChange(i.id)} title={collapsed?i.label:undefined}><span>{i.icon}</span>{!collapsed&&i.label}</button>)}</div>)}{extra.length>0&&<div className="nav-group">{!collapsed&&<div className="nav-title">Welt-System</div>}{extra.map(i=><button key={i.id} className={active===i.id?"active":""} onClick={()=>onChange(i.id)}><span>{i.icon}</span>{!collapsed&&i.label}</button>)}</div>}{showDev&&<div className="nav-group dev-group"><button className={active==="dev"?"active":""} onClick={()=>onChange("dev")}><span>⚙</span>{!collapsed&&"DEV / Test"}</button></div>}</nav></aside>
}
