import { CharacterStore } from "../db/memoryStore.js"; import { ValidationError } from "./characterService.js"; import { NINJA_TECHNIQUES,techniqueById } from "../data/ninjaTechniques.js"; import type{Character}from"../types/character.js";
function get(id:string){const c=CharacterStore.get(id);if(!c)throw new ValidationError("Charakter nicht gefunden");if(c.worldId!=="ninja_welt")throw new ValidationError("Nur Ninja können dieses Training nutzen.");c.chakraNatures??=[];return c}
function state(c:Character,id:string){let s=c.ninjaTechniques.find(x=>x.techniqueId===id);if(!s){s={techniqueId:id,mastery:0,learned:false,analysisPct:0,seenCount:0,copied:false};c.ninjaTechniques.push(s)}return s}
export const CHAKRA_NATURES=["Katon","Suiton","Raiton","Fūton","Doton"] as const;
export function selectChakraNatures(id:string,natures:string[]){
 const c=get(id); const clean=[...new Set((natures??[]).map(x=>String(x).trim()))];
 if(c.chakraNatures.length===2)throw new ValidationError("Deine zwei Chakra-Naturen wurden bereits festgelegt.");
 if(clean.length!==2)throw new ValidationError("Wähle genau zwei unterschiedliche Chakra-Naturen.");
 if(clean.some(x=>!CHAKRA_NATURES.includes(x as any)))throw new ValidationError("Ungültige Chakra-Natur.");
 c.chakraNatures=clean; c.kampfkraftComponents.training+=2; return CharacterStore.save(c);
}
export function listNinjaTraining(id:string){const c=get(id);return NINJA_TECHNIQUES.filter(t=>!t.hidden||state(c,t.id).analysisPct>0||state(c,t.id).learned).map(t=>{const s=state(c,t.id);let reason:string|null=null;if(t.clanRestriction&&!t.clanRestriction.includes(c.clanId??""))reason="Dein Clan hat keinen Zugang zu dieser Technik.";if(t.element&&!c.chakraNatures.includes(t.element)&&!s.copied)reason=`Benötigt Chakra-Natur ${t.element}.`;if(t.acquisitionMethod==="MASTER_TRAINING"&&!s.copied)reason="Du musst zuerst den passenden Meister entdecken oder die Technik vollständig analysieren.";if(t.requiredMastery&&s.mastery<t.requiredMastery)reason=`Benötigt ${t.requiredMastery}% Beherrschung.`;if(t.requiredDojutsuStage&&(!c.dojutsuState?.awakened||c.dojutsuState.stageIndex<t.requiredDojutsuStage))reason=`Benötigt Sharingan-Stufe ${t.requiredDojutsuStage}.`;return{...t,state:s,available:!reason,lockedReason:reason}})}
export function trainNinjaTechnique(id:string,techniqueId:string){const c=get(id),t=techniqueById(techniqueId);if(!t)throw new ValidationError("Technik unbekannt");const entry=listNinjaTraining(id).find(x=>x.id===techniqueId);if(!entry||!entry.available)throw new ValidationError(entry?.lockedReason??"Technik ist noch unbekannt.");const s=state(c,techniqueId);if(!s.learned){s.learned=true;s.mastery=10}else s.mastery=Math.min(100,s.mastery+10);c.kampfkraftComponents.training+=2;c.kampfkraftComponents.faehigkeiten+=1;return CharacterStore.save(c)}
export function clanTrainSharingan(id:string){const c=get(id);if(c.clanId!=="clan-uchiha")throw new ValidationError("Nur Uchiha besitzen Sharingan-Potenzial.");if(!c.dojutsuState)c.dojutsuState={definitionId:"sharingan",name:"Sharingan",awakened:false,stageIndex:0,mastery:0,activeOutsideCombat:false,personalAbilityIds:[],developmentLog:["Sharingan-Potenzial durch Clantraining erschlossen."]};else c.dojutsuState.mastery=Math.min(100,c.dojutsuState.mastery+10);return CharacterStore.save(c)}
export function awakenSharingan(id:string){const c=get(id);if(c.clanId!=="clan-uchiha"||!c.dojutsuState)throw new ValidationError("Zuerst Uchiha-Clantraining absolvieren.");if(c.dojutsuState.awakened)throw new ValidationError("Sharingan ist bereits erwacht.");if(c.kampfkraftComponents.training<4)throw new ValidationError("Du benötigst mehr praktische Trainingserfahrung, bevor das Sharingan erwachen kann.");c.dojutsuState.awakened=true;c.dojutsuState.stageIndex=1;c.dojutsuState.mastery=5;c.dojutsuState.developmentLog.push("Sharingan mit 1 Tomoe erwacht.");return CharacterStore.save(c)}
export function advanceSharingan(id:string){const c=get(id),d=c.dojutsuState;if(!d?.awakened||d.definitionId!=="sharingan")throw new ValidationError("Sharingan ist noch nicht erwacht.");const req=[0,25,55,85][d.stageIndex]??100;if(d.mastery<req)throw new ValidationError(`Deine Sharingan-Beherrschung reicht noch nicht aus (${d.mastery}/${req}%).`);if(d.stageIndex>=4)throw new ValidationError("Mangekyō ist bereits erreicht; persönliche Weiterentwicklung folgt später.");d.stageIndex++;d.mastery=Math.max(5,d.mastery-15);d.developmentLog.push(d.stageIndex===2?"2 Tomoe entwickelt.":d.stageIndex===3?"3 Tomoe entwickelt.":"Mangekyō Sharingan entwickelt.");return CharacterStore.save(c)}
export function recordTechniqueSeen(c:Character,techniqueId:string,sharinganStage:number){const t=techniqueById(techniqueId);if(!t)return;const s=state(c,techniqueId);s.seenCount++;const gain=Math.min(35,10+sharinganStage*6+(c.dojutsuState?.mastery??0)/10);s.analysisPct=Math.min(100,s.analysisPct+gain);if(s.analysisPct>=100&&t.copyable&&(!t.element||c.chakraNatures.includes(t.element)))s.copied=true;if(c.dojutsuState)c.dojutsuState.mastery=Math.min(100,c.dojutsuState.mastery+3)}

export function clanTrainByakugan(id:string){
 const c=get(id); if(c.clanId!=="clan-hyuga")throw new ValidationError("Nur Hyūga besitzen Byakugan-Potenzial.");
 if(!c.dojutsuState)c.dojutsuState={definitionId:"byakugan",name:"Byakugan",awakened:false,stageIndex:0,mastery:0,activeOutsideCombat:false,personalAbilityIds:[],developmentLog:["Byakugan-Potenzial durch Clantraining erschlossen."]};
 else c.dojutsuState.mastery=Math.min(100,c.dojutsuState.mastery+12);
 return CharacterStore.save(c)
}
export function awakenByakugan(id:string){
 const c=get(id); if(c.clanId!=="clan-hyuga"||c.dojutsuState?.definitionId!=="byakugan")throw new ValidationError("Zuerst Hyūga-Clantraining absolvieren.");
 if(c.dojutsuState.awakened)throw new ValidationError("Byakugan ist bereits erwacht.");
 if(c.dojutsuState.mastery<10)throw new ValidationError("Trainiere dein Byakugan-Potenzial weiter.");
 c.dojutsuState.awakened=true;c.dojutsuState.stageIndex=1;c.dojutsuState.mastery=10;c.dojutsuState.developmentLog.push("Byakugan erwacht: Chakra-Sicht und Tenketsu-Wahrnehmung verfügbar.");return CharacterStore.save(c)
}
