import { useEffect, useState } from "react";
import { api } from "../api/client";
import { Sidebar, type GameView } from "../components/Sidebar";
import { Dashboard } from "./Dashboard"; import { InventoryPage } from "./InventoryPage"; import { SkillsPage } from "./SkillsPage"; import { ProgressionPage } from "./ProgressionPage"; import { MapPage } from "./MapPage"; import { WorldEventsPage } from "./WorldEventsPage"; import { TerritoryPage } from "./TerritoryPage"; import { OrganizationsPage } from "./OrganizationsPage"; import { VillagePage } from "./VillagePage"; import { MissionsPage } from "./MissionsPage"; import { CombatPage } from "./CombatPage"; import { CrewPage } from "./CrewPage"; import { FusionPage } from "./FusionPage"; import { CharacterProfilePage } from "./CharacterProfilePage"; import { TravelPage } from "./TravelPage"; import { MarketplacePage } from "./MarketplacePage"; import { ShopPage } from "./ShopPage"; import { DevToolsPage } from "./DevToolsPage";
import type { Character, Faction } from "../types/models";
export function Game({character:initial,onExit}:{character:Character;onExit:()=>void}){
 const[character,setCharacter]=useState(initial),[faction,setFaction]=useState<Faction|null>(null),[view,setView]=useState<GameView>("overview"),[collapsed,setCollapsed]=useState(false),[error,setError]=useState<string|null>(null);
 useEffect(()=>{api.getFactions(character.worldId).then(fs=>setFaction(fs.find(f=>f.id===character.factionId)??{id:character.factionId,worldId:character.worldId,name:"Neutral",description:"Noch keine endgültige Fraktion.",playerAssignedRanks:[],baseSkills:[],corePowerLabel:"Relikt",corePowerStages:[]})).catch(e=>setError(e.message))},[character.worldId,character.factionId]);
 if(error)return <div className="center-state"><p className="error-text">{error}</p></div>; if(!faction)return <div className="center-state">Lade Nexus...</div>;
 const render=()=>{switch(view){case"overview":return <Dashboard character={character} faction={faction} onUpdated={setCharacter}/>;case"profile":return <CharacterProfilePage character={character} onUpdated={setCharacter}/>;case"inventory":return <InventoryPage character={character} onUpdated={setCharacter}/>;case"skills":return <SkillsPage character={character} faction={faction} onUpdated={setCharacter}/>;case"progression":return <ProgressionPage character={character} onUpdated={setCharacter}/>;case"map":return <MapPage character={character}/>;case"travel":return <TravelPage character={character} onUpdated={setCharacter}/>;case"events":return <WorldEventsPage character={character} onUpdated={setCharacter}/>;case"territory":return <TerritoryPage character={character}/>;case"organizations":return <OrganizationsPage character={character} onUpdated={setCharacter}/>;case"village":return <VillagePage character={character} onUpdated={setCharacter}/>;case"missions":return <MissionsPage character={character} onUpdated={setCharacter}/>;case"combat":return <CombatPage character={character} onUpdated={setCharacter}/>;case"crew":return <CrewPage character={character} onUpdated={setCharacter}/>;case"fusion":return <FusionPage character={character}/>;case"marketplace":return <MarketplacePage character={character} onUpdated={setCharacter}/>;case"shop":return <ShopPage character={character} onUpdated={setCharacter}/>;case"dev":return import.meta.env.DEV?<DevToolsPage character={character} onUpdated={setCharacter}/>:<Dashboard character={character} faction={faction} onUpdated={setCharacter}/>;}};
 return <div className="game-shell"><Sidebar active={view} onChange={setView} worldId={character.worldId} collapsed={collapsed} showDev={import.meta.env.DEV} onToggle={()=>setCollapsed(v=>!v)}/><section className="game-main"><header className="topbar"><div><span className="eyebrow">{character.worldId.replaceAll("_"," ")}</span><h2>{character.characterName}</h2></div><div className="topbar-stats"><span><small>Kampfkraft</small><b>{character.kampfkraft??0}</b></span><span><small>{character.energy.label}</small><b>{character.energy.current}/{character.energy.max}</b></span><span><small>Gold</small><b>{character.gold}</b></span><button className="secondary-button" onClick={onExit}>Charakter wechseln</button></div></header><main className="content-area">{render()}</main></section></div>
}
