import {useEffect,useState} from "react";import{api}from"../api/client";import type{Character,Faction,NinjaTrainingEntry}from"../types/models";
const card={border:"1px solid #d8dce5",borderRadius:10,padding:12,background:"#fff"};
export function SkillsPage({character,faction,onUpdated}:{character:Character;faction:Faction;onUpdated:(c:Character)=>void}){const[error,setError]=useState<string|null>(null),[busy,setBusy]=useState<string|null>(null),[ninja,setNinja]=useState<NinjaTrainingEntry[]>([]);
const reload=()=>character.worldId==="ninja_welt"?api.getNinjaTraining(character.id).then(setNinja).catch(e=>setError(e.message)):Promise.resolve();useEffect(()=>{reload()},[character.id,character.worldId,character.ninjaTechniques.length,character.dojutsuState?.mastery]);
async function run(key:string,fn:()=>Promise<Character>){setBusy(key);setError(null);try{onUpdated(await fn());await reload()}catch(e){setError(e instanceof Error?e.message:"Fehler")}finally{setBusy(null)}}
if(character.worldId==="ninja_welt"){const d=character.dojutsuState;return <section><h2>Training & Fähigkeiten</h2><p>Hier entwickelst du Jutsu, Clan-Techniken und persönliche Kräfte. Gesperrte Inhalte erklären dir den bekannten Teil der Voraussetzung.</p>{error&&<p className="error-text">{error}</p>}
<div style={{display:"grid",gap:14}}><div style={card}><h3>Grundtraining</h3><p>Statpunkte: <b>{character.statPoints}</b> · Chakra {character.energy.current}/{character.energy.max}</p><small>Stats verteilst du im Charakterprofil. Jutsu werden hier separat trainiert.</small></div>
{character.clanId==="clan-uchiha"&&<div style={card}><h3>Uchiha-Clantraining</h3>{!d?<><p>In dir liegt Sharingan-Potenzial. Clantraining erschließt zunächst nur das Potenzial – nicht das fertige Auge.</p><button disabled={!!busy} onClick={()=>run("clan",()=>api.sharinganClanTraining(character.id))}>Sharingan-Potenzial trainieren</button></>:!d.awakened?<><p><b>Sharingan-Potenzial erschlossen</b> · Vorbereitung/Mastery {d.mastery}%</p><button disabled={!!busy} onClick={()=>run("clan",()=>api.sharinganClanTraining(character.id))}>Clantraining fortsetzen</button> <button disabled={!!busy} onClick={()=>run("awake",()=>api.awakenSharingan(character.id))}>Erwachen versuchen</button></>:<><p><b>Sharingan · {d.stageIndex===4?"Mangekyō":`${d.stageIndex} Tomoe`}</b></p><Progress value={d.mastery}/><p>Beherrschung: {d.mastery}%</p><button disabled={!!busy} onClick={()=>run("clan",()=>api.sharinganClanTraining(character.id))}>Sharingan trainieren</button> <button disabled={!!busy} onClick={()=>run("advance",()=>api.advanceSharingan(character.id))}>Nächste Entwicklung prüfen</button></>}</div>}
<div><h3>Jutsu-Training</h3><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))",gap:10}}>{ninja.map(t=><div key={t.id} style={{...card,opacity:t.available?1:.72}}><b>{t.name}</b><p style={{fontSize:13}}>{t.description}</p><small>{t.category}{t.element?` · ${t.element}`:""} · {t.baseCost} Chakra</small><Progress value={t.state.mastery}/><div style={{fontSize:12}}>Mastery {t.state.mastery}% {t.state.analysisPct>0&&`· Analyse ${Math.round(t.state.analysisPct)}%`}</div>{t.available?<button disabled={!!busy} onClick={()=>run(t.id,()=>api.trainNinjaTechnique(character.id,t.id))}>{t.state.learned?"Weiter trainieren":"Lernen"}</button>:<p style={{fontSize:12,color:"#8a5a00"}}>🔒 {t.lockedReason}</p>}</div>)}</div></div>
<div style={card}><h3>Analysierte Techniken</h3>{ninja.filter(t=>t.state.analysisPct>0).length?ninja.filter(t=>t.state.analysisPct>0).map(t=><p key={t.id}>{t.name}: <b>{Math.round(t.state.analysisPct)}%</b>{t.state.copied?" · vollständig analysiert / trainierbar":""}{!t.copyable?" · nicht kopierbar":""}</p>):<p>Noch keine gegnerische Technik analysiert. Ein aktives Sharingan kann im Kampf Techniken erfassen.</p>}</div></div></section>}
return <section><h2>Fähigkeiten von {faction.name}</h2>{error&&<p className="error-text">{error}</p>}<div style={{display:"grid",gap:8}}>{faction.baseSkills.map(name=>{const level=character.skills.find(s=>s.name===name)?.level??0;return <div key={name} style={card}><span>{name} — Stufe {level}</span><button onClick={()=>run(name,()=>api.trainSkill(character.id,name))}>Trainieren</button></div>})}</div></section>}
function Progress({value}:{value:number}){return <div style={{height:7,background:"#e8eaf0",borderRadius:5,margin:"8px 0",overflow:"hidden"}}><div style={{height:"100%",width:`${Math.max(0,Math.min(100,value))}%`,background:"#6677cc"}}/></div>}
